export const MUTATIONS = {
   SET_STATUS: "SET_STATUS",
   SET_USER: "SET_USER",
   SET_MODAL: "SET_MODAL"
}

export const ACTIONS = {
   AUTHENTICATE_USER: "AUTHENTICATE_USER",
   TOGGLE_MODAL: "TOGGLE_MODAL"
}